//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaderTranslator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslatorInternal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslatorInternal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShaderTranslator.Resources.TranslatorInternal", typeof(TranslatorInternal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cbuffer cbGlobalsPS : register(b0)
        ///{
        ///    // x = params.brightness
        ///    // y = params.contrast
        ///    // z = params.hue
        ///    // w = params.saturation
        ///    float4 cY : packoffset(c150);
        ///}
        ///
        ///Texture2D&lt;float4&gt; s0 : register(t0);
        ///SamplerState s0_s : register(s0);
        ///
        ///#define EPSILON 1e-10
        ///
        ///float3 hue2rgb(in float H)
        ///{
        ///	float r = abs(H * 6 - 3) - 1;
        ///	float g = 2 - abs(H * 6 - 2);
        ///	float b = 2 - abs(H * 6 - 4);
        ///	return saturate(float3(r, g, b));
        ///}
        ///
        ///float3 rgb2ybr(in float3 rgb)
        ///{
        ///	float y = dot(rgb,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ColorCorrection {
            get {
                return ResourceManager.GetString("ColorCorrection", resourceCulture);
            }
        }
    }
}
